# Lab | Data Cleaning and Formatting

In this lab, we will be working with the customer data from an insurance company, which can be found in the CSV file located at the following link: https://raw.githubusercontent.com/data-bootcamp-v4/data/main/file1.csv

# Challenge 1: Data Cleaning and Formatting

## Exercise 1: Cleaning Column Names

To ensure consistency and ease of use, standardize the column names of the dataframe. Start by taking a first look at the dataframe and identifying any column names that need to be modified. Use appropriate naming conventions and make sure that column names are descriptive and informative.

*Hint*: 
- *Column names should be in lower case*
- *White spaces in column names should be replaced by `_`*
- *`st` could be replaced for `state`*

In [1]:
import pandas as pd
url = 'https://raw.githubusercontent.com/data-bootcamp-v4/data/main/file1.csv'
df = pd.read_csv(url)

In [2]:
df.columns

Index(['Customer', 'ST', 'GENDER', 'Education', 'Customer Lifetime Value',
       'Income', 'Monthly Premium Auto', 'Number of Open Complaints',
       'Policy Type', 'Vehicle Class', 'Total Claim Amount'],
      dtype='str')

In [3]:
df.columns = df.columns.str.lower().str.replace(" ", "_")
df = df.rename(columns={"st": "state"})

In [4]:
df.columns

Index(['customer', 'state', 'gender', 'education', 'customer_lifetime_value',
       'income', 'monthly_premium_auto', 'number_of_open_complaints',
       'policy_type', 'vehicle_class', 'total_claim_amount'],
      dtype='str')

## Exercise 2: Cleaning invalid Values

The dataset contains columns with inconsistent and incorrect values that could affect the accuracy of our analysis. Therefore, we need to clean these columns to ensure that they only contain valid data.

Note that this exercise will focus only on cleaning inconsistent values and will not involve handling null values (NaN or None).

*Hint*:
- *Gender column contains various inconsistent values such as "F", "M", "Femal", "Male", "female", which need to be standardized, for example, to "M" and "F".*
- *State abbreviations be can replaced with its full name, for example "AZ": "Arizona", "Cali": "California", "WA": "Washington"*
- *In education, "Bachelors" could be replaced by "Bachelor"*
- *In Customer Lifetime Value, delete the `%` character*
- *In vehicle class, "Sports Car", "Luxury SUV" and "Luxury Car" could be replaced by "Luxury"*

In [5]:
df["gender"] = df["gender"].replace({"Femal": "F", "Male": "M", "female": "F"})
df["state"] = df["state"].replace({"Cali": "California", "WA": "Washington", "AZ": "Arizona"})
df["education"] = df["education"].replace({"Bachelors": "Bachelor",})

In [6]:
df["customer_lifetime_value"] = df["customer_lifetime_value"].str.replace("%", "")
df["vehicle_class"] = df["vehicle_class"].replace(["Sports Car", "Luxury SUV", "Luxury Car"], "Luxury",)

## Exercise 3: Formatting data types

The data types of many columns in the dataset appear to be incorrect. This could impact the accuracy of our analysis. To ensure accurate analysis, we need to correct the data types of these columns. Please update the data types of the columns as appropriate.

It is important to note that this exercise does not involve handling null values (NaN or None).

*Hint*:
- *Customer lifetime value should be numeric*
- *Number of open complaints has an incorrect format. Look at the different values it takes with `unique()` and take the middle value. As an example, 1/5/00 should be 5. Number of open complaints is a string - remember you can use `split()` to deal with it and take the number you need. Finally, since it should be numeric, cast the column to be in its proper type.*

In [7]:
df.dtypes

customer                         str
state                            str
gender                           str
education                        str
customer_lifetime_value          str
income                       float64
monthly_premium_auto         float64
number_of_open_complaints        str
policy_type                      str
vehicle_class                    str
total_claim_amount           float64
dtype: object

In [8]:
df["customer_lifetime_value"] = df["customer_lifetime_value"].astype(float)

In [9]:
df["number_of_open_complaints"].unique()

<StringArray>
['1/0/00', '1/2/00', '1/1/00', '1/3/00', '1/5/00', '1/4/00', nan]
Length: 7, dtype: str

In [10]:
df["number_of_open_complaints"] = df["number_of_open_complaints"].str.split("/").str[1].astype("Int64")

In [11]:
df["number_of_open_complaints"].dtype

Int64Dtype()

## Exercise 4: Dealing with Null values

Identify any columns with null or missing values. Identify how many null values each column has. You can use the `isnull()` function in pandas to find columns with null values.

Decide on a strategy for handling the null values. There are several options, including:

- Drop the rows or columns with null values
- Fill the null values with a specific value (such as the column mean or median for numerical variables, and mode for categorical variables)
- Fill the null values with the previous or next value in the column
- Fill the null values based on a more complex algorithm or model (note: we haven't covered this yet)

Implement your chosen strategy to handle the null values. You can use the `fillna()` function in pandas to fill null values or `dropna()` function to drop null values.

Verify that your strategy has successfully handled the null values. You can use the `isnull()` function again to check if there are still null values in the dataset.

Remember to document your process and explain your reasoning for choosing a particular strategy for handling null values.

After formatting data types, as a last step, convert all the numeric variables to integers.

In [12]:
df.isnull().sum()

customer                     2937
state                        2937
gender                       3054
education                    2937
customer_lifetime_value      2940
income                       2937
monthly_premium_auto         2937
number_of_open_complaints    2937
policy_type                  2937
vehicle_class                2937
total_claim_amount           2937
dtype: int64

In [13]:
df.isnull().sum()

customer                     2937
state                        2937
gender                       3054
education                    2937
customer_lifetime_value      2940
income                       2937
monthly_premium_auto         2937
number_of_open_complaints    2937
policy_type                  2937
vehicle_class                2937
total_claim_amount           2937
dtype: int64

In [14]:
df = df.dropna()

In [15]:
df.dtypes

customer                         str
state                            str
gender                           str
education                        str
customer_lifetime_value      float64
income                       float64
monthly_premium_auto         float64
number_of_open_complaints      Int64
policy_type                      str
vehicle_class                    str
total_claim_amount           float64
dtype: object

In [16]:
df["customer_lifetime_value"] = df["customer_lifetime_value"].astype(int)
df["income"] = df["income"].astype(int)
df["monthly_premium_auto"] = df["monthly_premium_auto"].astype(int)
df["total_claim_amount"] = df["total_claim_amount"].astype(int)

In [17]:
df.dtypes

customer                       str
state                          str
gender                         str
education                      str
customer_lifetime_value      int64
income                       int64
monthly_premium_auto         int64
number_of_open_complaints    Int64
policy_type                    str
vehicle_class                  str
total_claim_amount           int64
dtype: object

## Exercise 5: Dealing with duplicates

Use the `.duplicated()` method to identify any duplicate rows in the dataframe.

Decide on a strategy for handling the duplicates. Options include:
- Dropping all duplicate rows
- Keeping only the first occurrence of each duplicated row
- Keeping only the last occurrence of each duplicated row
- Dropping duplicates based on a subset of columns
- Dropping duplicates based on a specific column

Implement your chosen strategy using the `drop_duplicates()` function.

Verify that your strategy has successfully handled the duplicates by checking for duplicates again using `.duplicated()`.

Remember to document your process and explain your reasoning for choosing a particular strategy for handling duplicates.

Save the cleaned dataset to a new CSV file.

*Hint*: *after dropping duplicates, reset the index to ensure consistency*.

In [18]:
df.duplicated().sum()

np.int64(0)

In [19]:
df = df.drop_duplicates()

In [20]:
df = df.reset_index(drop=True)

In [21]:
df.duplicated().sum()

np.int64(0)

In [22]:
df.to_csv("df_cleaned.csv", index=False)

# Bonus: Challenge 2: creating functions on a separate `py` file

Put all the data cleaning and formatting steps into functions, and create a main function that performs all the cleaning and formatting.

Write these functions in separate .py file(s). By putting these steps into functions, we can make the code more modular and easier to maintain.

*Hint: autoreload module is a utility module in Python that allows you to automatically reload modules in the current session when changes are made to the source code. This can be useful in situations where you are actively developing code and want to see the effects of changes you make without having to constantly restart the Python interpreter or Jupyter Notebook kernel.*

In [23]:
%load_ext autoreload
%autoreload 2

In [24]:
from cleaning import main

In [25]:
df = main()

In [26]:
df.shape

(952, 11)

In [27]:
df.isnull().sum()

customer                     0
state                        0
gender                       0
education                    0
customer_lifetime_value      0
income                       0
monthly_premium_auto         0
number_of_open_complaints    0
policy_type                  0
vehicle_class                0
total_claim_amount           0
dtype: int64

In [28]:
df.duplicated().sum()

np.int64(0)

In [29]:
df.to_csv("df_cleaned.csv", index=False)

In [30]:
df = main()

# Bonus: Challenge 3: Analyzing Clean and Formated Data

You have been tasked with analyzing the data to identify potential areas for improving customer retention and profitability. Your goal is to identify customers with a high policy claim amount and a low customer lifetime value.

In the Pandas Lab, we only looked at high policy claim amounts because we couldn't look into low customer lifetime values. If we had tried to work with that column, we wouldn't have been able to because customer lifetime value wasn't clean and in its proper format. So after cleaning and formatting the data, let's get some more interesting insights!

Instructions:

- Review the statistics again for total claim amount and customer lifetime value to gain an understanding of the data.
- To identify potential areas for improving customer retention and profitability, we want to focus on customers with a high policy claim amount and a low customer lifetime value. Consider customers with a high policy claim amount to be those in the top 25% of the total claim amount, and clients with a low customer lifetime value to be those in the bottom 25% of the customer lifetime value. Create a pandas DataFrame object that contains information about customers with a policy claim amount greater than the 75th percentile and a customer lifetime value in the bottom 25th percentile.
- Use DataFrame methods to calculate summary statistics about the high policy claim amount and low customer lifetime value data. To do so, select both columns of the dataframe simultaneously and pass it to the `.describe()` method. This will give you descriptive statistics, such as mean, median, standard deviation, minimum and maximum values for both columns at the same time, allowing you to compare and analyze their characteristics.

In [31]:
df[["total_claim_amount", "customer_lifetime_value"]].describe()

       total_claim_amount  customer_lifetime_value
count          952.000000             9.520000e+02
mean           404.544118             7.942008e+05
std            299.252620             6.258791e+05
min              0.000000             2.004350e+05
25%            196.000000             4.117828e+05
50%            350.000000             5.885740e+05
75%            533.250000             9.037502e+05
max           2893.000000             4.479546e+06

In [32]:
df["total_claim_amount"].quantile(0.75)

np.float64(533.25)

In [33]:
df["customer_lifetime_value"].quantile(0.25)

np.float64(411782.75)

In [34]:
df_filtered = df[
    (df["total_claim_amount"] > 532) &
    (df["customer_lifetime_value"] < 405404.5)
]

In [35]:
df_filtered.shape

(33, 11)

In [36]:
df_filtered[["total_claim_amount", "customer_lifetime_value"]].describe()

       total_claim_amount  customer_lifetime_value
count           33.000000                33.000000
mean           714.060606            339083.090909
std            149.122420             56918.610535
min            537.000000            228759.000000
25%            632.000000            289873.000000
50%            679.000000            365253.000000
75%            773.000000            383960.000000
max           1185.000000            402381.000000

In [37]:
# Estos 40 clientes podrían ser un grupo interesante para analizar, ya que combinan reclamaciones elevadas con un valor de cliente bajo. La empresa podría investigas por qué generan reclamaciones altas y estudiar cómo mejorar su retención.